name: Create release on tag push

on:
  push:
    tags:
      - 'release/*'

jobs:
  build:
    name: Build VoiceAttack-EliteScreenshots
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Setup .Net
        uses: actions/setup-dotnet@v2

      - name: Build
        run: dotnet build -c release

      - name: Draft release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "VoiceAttack-EliteScreenshots.zip"
          bodyFile: "CHANGELOG.md"
          draft: true
